timeout: 1200s
substitutions:
  _CUSTOM_REGION: europe-west3-a
  _CUSTOM_CLUSTER: schedulytics
steps:
  # PREPARATION of kubectl and helm
  - name: gcr.io/cloud-builders/kubectl
    id: Configure kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config

  - name: gcr.io/$PROJECT_ID/helm
    id: Add jetstack repository for cert-manager
    args:
      - repo
      - add
      - jetstack
      - https://charts.jetstack.io
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - name: gcr.io/$PROJECT_ID/helm
    id: Add traefik repository for traefik
    args:
      - repo
      - add
      - traefik
      - https://containous.github.io/traefik-helm-chart
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - name: gcr.io/$PROJECT_ID/helm
    id: Add bitnami repository for mongodb
    args:
      - repo
      - add
      - bitnami
      - https://charts.bitnami.com/bitnami
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - name: gcr.io/$PROJECT_ID/helm
    id: Add stable repository for envoy
    args:
      - repo
      - add
      - stable
      - https://kubernetes-charts.storage.googleapis.com/
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  # Provide secrets
  - name: gcr.io/cloud-builders/gcloud
    id: Acquire secrets from SecretManager
    entrypoint: 'bash'
    args: 
      - '-c'
      - | 
          mkdir secrets
          gcloud secrets versions access latest --secret=schedulytics-environment-ssh > secrets/schedulytics-cert-manager-sa
          gcloud secrets versions access latest --secret=schedulytics-mongodb-root-password	> secrets/schedulytics-mongodb-root-password
          gcloud secrets versions access latest --secret=schedulytics-mongodb-user-password > secrets/schedulytics-mongodb-user-password

  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'Create required Kubernetes secrets'
    args:
      - 'apply'
      - '--filename=./cert-manager/secrets.yaml'
    env:
      - KUBECONFIG=/workspace/.kube/config
      - SCHEDULYTICS_CERT_MANAGER_SA=$(cat secrets/schedulytics-cert-manager-sa)
  
  # DEPLOYMENT of environment
  - name: gcr.io/$PROJECT_ID/helm
    id: Deploy cert-manager
    args:
      - upgrade
      - -i
      - cert-manager
      - --namespace
      - cert-manager
      - jetstack/cert-manager
      - -f
      - ./cert-manager/values.yaml
      - --version
      - v0.15.1
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - name: gcr.io/$PROJECT_ID/helm
    id: Deploy traefik
    args:
      - upgrade
      - -i
      - traefik
      - --namespace
      - default
      - traefik/traefik
      - -f
      - ./traefik/values.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - name: gcr.io/$PROJECT_ID/helm
    id: Deploy mongodb
    args:
      - upgrade
      - -i
      - mongodb
      - --namespace
      - default
      - bitnami/mongodb
      - -f
      - ./mongodb/values.yaml
      - --set
      - mongodbRootPassword=${MONGODB_ROOT_PW}
      - --set
      - mongodbPassword=${MONGODB_USER_PW}
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true
      - MONGODB_ROOT_PW=$(cat secrets/schedulytics-mongodb-root-password)
      - MONGODB_USER_PW=$(cat secrets/schedulytics-mongodb-user-password)

  - name: gcr.io/$PROJECT_ID/helm
    id: Deploy schedulytics-frontend
    args:
      - upgrade
      - -i
      - schedulytics-frontend
      - --namespace
      - default
      - ./schedulytics-frontend
      - -f
      - ./schedulytics-frontend/values.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - name: gcr.io/$PROJECT_ID/helm
    id: Deploy schedulytics-grpc-server
    args:
      - upgrade
      - -i
      - schedulytics-grpc-server
      - --namespace
      - default
      - ./schedulytics-grpc-server
      - -f
      - ./schedulytics-grpc-server/values.yaml
      - --set
      - database.password=${MONGODB_USER_PW}
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true
      - MONGODB_USER_PW=$(cat secrets/schedulytics-mongodb-user-password)

  - name: gcr.io/$PROJECT_ID/helm
    id: Deploy envoy
    args:
      - upgrade
      - -i
      - envoy
      - --namespace
      - default
      - stable/envoy
      - -f
      - ./envoy/values.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  # Apply additional configuration
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'Apply cert-manager certificate configuration'
    args:
      - 'apply'
      - '--filename=./cert-manager/certs.yaml'
    env:
      - KUBECONFIG=/workspace/.kube/config

  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'Apply traefik routes configuration'
    args:
      - 'apply'
      - '--filename=./traefik/routes.yaml'
    env:
      - KUBECONFIG=/workspace/.kube/config