timeout: 1200s
substitutions:
  _CUSTOM_REGION: europe-west3-a
  _CUSTOM_CLUSTER: schedulytics
  _CUSTOM_BUILDTARGET: prod

steps:
  # PREPARATION of kubectl and helm
  - id: Configure kubectl
    name: gcr.io/cloud-builders/kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config

    # Prepare python
  - id: Get python version
    name: gcr.io/$PROJECT_ID/helm
    entrypoint: /bin/bash
    args:
      - -c
      - |
        sudo apt-get install python3-pip
        python3 --version
        python3 -m pip install pyyaml

  - id: Add jetstack repository for cert-manager
    name: gcr.io/$PROJECT_ID/helm
    args:
      - repo
      - add
      - jetstack
      - https://charts.jetstack.io
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - id: Add traefik repository for traefik
    name: gcr.io/$PROJECT_ID/helm
    args:
      - repo
      - add
      - traefik
      - https://containous.github.io/traefik-helm-chart
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - id: Add bitnami repository for mongodb
    name: gcr.io/$PROJECT_ID/helm
    args:
      - repo
      - add
      - bitnami
      - https://charts.bitnami.com/bitnami
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - id: Add stable repository for envoy
    name: gcr.io/$PROJECT_ID/helm
    args:
      - repo
      - add
      - stable
      - https://kubernetes-charts.storage.googleapis.com/
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  # Provide secrets
  - id: Acquire secrets from SecretManager
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: 
      - -c
      - | 
          mkdir charts/cert-manager/kustomize/$${BUILDTARGET}/secrets
          mkdir charts/mongodb/kustomize/$${BUILDTARGET}/secrets
          mkdir charts/schedulytics-grpc-server/kustomize/$${BUILDTARGET}/secrets
          gcloud secrets versions access latest --secret=schedulytics-environment-ssh > charts/cert-manager/kustomize/$${BUILDTARGET}/secrets/key.json
          gcloud secrets versions access latest --secret=schedulytics-mongodb-root-password	> charts/mongodb/kustomize/$${BUILDTARGET}/secrets/schedulytics-mongodb-root-password
          gcloud secrets versions access latest --secret=schedulytics-mongodb-user-password > charts/mongodb/kustomize/$${BUILDTARGET}/secrets/schedulytics-mongodb-user-password
          gcloud secrets versions access latest --secret=schedulytics-mongodb-user-password > charts/schedulytics-grpc-server/kustomize/$${BUILDTARGET}/secrets/schedulytics-mongodb-user-password
    env:
      - BUILDTARGET=$_CUSTOM_BUILDTARGET

  # Templating via Helm
  - id: Template cert-manager
    name: gcr.io/$PROJECT_ID/helm
    entrypoint: /bin/bash
    dir: charts/cert-manager
    args:
      - -c
      - >
        helm upgrade cert-manager
        --install
        --create-namespace
        --namespace cert-manager
        -f values.yaml
        --version v0.15.1
        --post-renderer /workspace/build/kustomize.py
        jetstack/cert-manager
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true
      - BUILDTARGET=$_CUSTOM_BUILDTARGET

  - id: Template traefik
    name: gcr.io/$PROJECT_ID/helm
    entrypoint: /bin/bash
    dir: charts/traefik
    args:
      - -c
      - >
        helm upgrade traefik
        --install
        --create-namespace
        --namespace traefik
        -f values.yaml
        --post-renderer /workspace/build/kustomize.py
        traefik/traefik
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true
      - BUILDTARGET=$_CUSTOM_BUILDTARGET

  - id: Template envoy
    name: gcr.io/$PROJECT_ID/helm
    entrypoint: /bin/bash
    dir: charts/envoy
    args:
      - -c
      - >
        helm upgrade -i envoy
        --create-namespace
        --namespace schedulytics
        -f values.yaml
        stable/envoy
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - id: Template mongodb
    name: gcr.io/$PROJECT_ID/helm
    entrypoint: /bin/bash
    dir: charts/mongodb
    args:
      - -c
      - >
        helm upgrade -i mongodb
        --create-namespace
        --namespace schedulytics
        -f values.yaml
        --post-renderer /workspace/build/kustomize.py
        bitnami/mongodb
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true
      - BUILDTARGET=$_CUSTOM_BUILDTARGET

  - id: Template schedulytics-frontend
    name: gcr.io/$PROJECT_ID/helm
    entrypoint: /bin/bash
    dir: charts/schedulytics-frontend
    args:
      - -c
      - >
        helm upgrade -i schedulytics-frontend
        --create-namespace
        --namespace schedulytics
        -f values.yaml
        .
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - id: Template schedulytics-grpc-server
    name: gcr.io/$PROJECT_ID/helm
    entrypoint: /bin/bash
    dir: charts/schedulytics-grpc-server
    args:
      - -c
      - >
        helm upgrade -i schedulytics-grpc-server
        --create-namespace
        --namespace schedulytics
        -f values.yaml
        --post-renderer /workspace/build/kustomize.py
        .
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true
      - BUILDTARGET=$_CUSTOM_BUILDTARGET

  - id: Debug repo after CD
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: 
      - -c
      - | 
          ls -ltR .
    env:
      - BUILDTARGET=$_CUSTOM_BUILDTARGET