timeout: 1200s
substitutions:
  _CUSTOM_REGION: europe-west3-a
  _CUSTOM_CLUSTER: schedulytics

steps:
  # PREPARATION of kubectl and helm
  - id: Configure kubectl
    name: gcr.io/cloud-builders/kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config

  - id: Add jetstack repository for cert-manager
    name: gcr.io/$PROJECT_ID/helm
    args:
      - repo
      - add
      - jetstack
      - https://charts.jetstack.io
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - id: Add traefik repository for traefik
    name: gcr.io/$PROJECT_ID/helm
    args:
      - repo
      - add
      - traefik
      - https://containous.github.io/traefik-helm-chart
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - id: Add bitnami repository for mongodb
    name: gcr.io/$PROJECT_ID/helm
    args:
      - repo
      - add
      - bitnami
      - https://charts.bitnami.com/bitnami
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - id: Add stable repository for envoy
    name: gcr.io/$PROJECT_ID/helm
    args:
      - repo
      - add
      - stable
      - https://kubernetes-charts.storage.googleapis.com/
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  # Provide secrets
  - id: Acquire secrets from SecretManager
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: 
      - -c
      - | 
          mkdir overlays/prod/secrets
          gcloud secrets versions access latest --secret=schedulytics-environment-ssh > overlays/prod/secrets/key.json
          gcloud secrets versions access latest --secret=schedulytics-mongodb-root-password	> overlays/prod/secrets/schedulytics-mongodb-root-password
          gcloud secrets versions access latest --secret=schedulytics-mongodb-user-password > overlays/prod/secrets/schedulytics-mongodb-user-password
  
  # Templating via Helm
  - id: Template cert-manager
    name: gcr.io/$PROJECT_ID/helm
    entrypoint: /bin/bash
    args:
      - -c
      - >
        helm template cert-manager
        --create-namespace
        --namespace cert-manager
        -f ./bases/cert-manager/values.yaml
        --version v0.15.1
        jetstack/cert-manager
        > ./bases/cert-manager/helm.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - id: Template traefik
    name: gcr.io/$PROJECT_ID/helm
    entrypoint: /bin/bash
    args:
      - -c
      - >
        helm template traefik
        --namespace default
        -f ./bases/traefik/values.yaml
        traefik/traefik
        > ./bases/traefik/helm.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - id: Template envoy
    name: gcr.io/$PROJECT_ID/helm
    entrypoint: /bin/bash
    args:
      - -c
      - >
        helm template envoy
        --namespace default
        -f ./bases/envoy/values.yaml
        stable/envoy
        > ./bases/envoy/helm.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - id: Template mongodb
    name: gcr.io/$PROJECT_ID/helm
    entrypoint: /bin/bash
    args:
      - -c
      - >
        helm template mongodb
        --namespace default
        -f ./bases/mongodb/values.yaml
        bitnami/mongodb
        > ./bases/mongodb/helm.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - id: Template schedulytics-frontend
    name: gcr.io/$PROJECT_ID/helm
    entrypoint: /bin/bash
    args:
      - -c
      - >
        helm template schedulytics-frontend
        --namespace default
        -f ./bases/schedulytics-frontend/values.yaml
        ./bases/schedulytics-frontend
        > ./bases/schedulytics-frontend/helm.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  - id: Template schedulytics-grpc-server
    name: gcr.io/$PROJECT_ID/helm
    entrypoint: /bin/bash
    args:
      - -c
      - >
        helm template schedulytics-grpc-server
        --namespace default
        -f ./bases/schedulytics-grpc-server/values.yaml
        ./bases/schedulytics-grpc-server
        > ./bases/schedulytics-grpc-server/helm.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true

  # DEPLOY via kustomize
  - id: Deploy PROD configuration via Kustomize
    name: 'gcr.io/$PROJECT_ID/kustomize'
    args:
    - build
    - overlays/prod
    env:
      - APPLY=true
      - KUBECONFIG=/workspace/.kube/config