# Default values for go-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/schedulytics-278820/schedulytics-frontend
  tag: 0b6a22dfc5d9b4459694f8d940440c9f7e4f3d50
  pullPolicy: IfNotPresent
service:
  name: schedulytics-frontend
  type: NodePort
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi
