---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: denolte-com
  namespace: traefik
spec:
  secretName: denolte-com-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - 'denolte.com'
  - '*.denolte.com'