---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: hello@denolte.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: issuer-account-key
    solvers:
    - dns01:
        clouddns:
          # The ID of the GCP project
          project: schedulytics-278820
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: denolte-com
  namespace: cert-manager
spec:
  secretName: denolte-com-tls
  issuerRef:
    name: letsencrypt
    kind: Issuer
  dnsNames:
  - 'denolte.com'
  - '*.denolte.com'